# Generated by Django 2.1.4 on 2019-03-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupnews', '0002_groupnews_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupnews',
            name='converted_news',
            field=models.TextField(default=''),
        ),
    ]
