# Generated by Django 2.1.5 on 2019-10-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupnews', '0003_groupnews_converted_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupnews',
            name='plaintext_news',
            field=models.TextField(default=''),
        ),
    ]
