# Generated by Django 2.1 on 2018-08-03 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='stripe_payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='stripepayment.Payment'),
        ),
    ]
