# Generated by Django 2.1.4 on 2019-01-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_auto_20190126_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donated_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
