# Generated by Django 2.1.4 on 2019-01-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_donation_donated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
