# Generated by Django 2.1.4 on 2019-01-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0007_donation_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='is_anonymous',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
