# Generated by Django 2.1.1 on 2018-09-18 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taigaissuecreator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaigaIssueAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ImageField(upload_to='')),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='taigaissuecreator.TaigaIssue')),
            ],
        ),
    ]
