# Generated by Django 2.1.4 on 2018-12-19 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(max_length=100)),
                ('charged_for', models.CharField(choices=[('COIN_PURCHASE', 'COIN_PURCHASE'), ('DONATION', 'DONATION')], max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('EXPIRED', 'EXPIRED'), ('UNRESOLVED', 'UNRESOLVED'), ('RESOLVED', 'RESOLVED'), ('CANCELED', 'CANCELED')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('charged_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChargePricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(default='', max_length=100)),
                ('bitcoin', models.CharField(default='', max_length=100)),
                ('bitcoincash', models.CharField(default='', max_length=100)),
                ('litecoin', models.CharField(default='', max_length=100)),
                ('ethereum', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='charge',
            name='pricing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coinbasepay.ChargePricing'),
        ),
    ]
