# Generated by Django 2.1.4 on 2018-12-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinbasepay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='charge_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
