# Generated by Django 2.1.4 on 2018-12-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinbasepay', '0003_auto_20181219_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='charged_for_related_task_is_done',
            field=models.BooleanField(default=False),
        ),
    ]
