# Generated by Django 2.1.4 on 2018-12-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinbasepay', '0004_charge_charged_for_related_task_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='charged_for',
            field=models.CharField(choices=[('PROXC_COIN_PURCHASE', 'PROXC_COIN_PURCHASE'), ('DONATION', 'DONATION')], max_length=20),
        ),
    ]
