# Generated by Django 2.1.4 on 2018-12-27 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coinbasepay', '0006_auto_20181223_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localamount', models.CharField(default='', max_length=100)),
                ('localcurrency', models.CharField(default='USD', max_length=100)),
                ('cryptoamount', models.CharField(default='', max_length=100)),
                ('cryptocurrency', models.CharField(default='', max_length=100)),
                ('txid', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='charge',
            name='charge_status_context',
            field=models.CharField(choices=[('OVERPAID', 'OVERPAID'), ('UNDERPAID', 'UNDERPAID'), ('MULTIPLE', 'MULTIPLE'), ('DELAYED', 'DELAYED'), ('MANUAL', 'MANUAL'), ('OTHER', 'OTHER')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='chargepayment',
            name='charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='coinbasepay.Charge'),
        ),
    ]
