# Generated by Django 2.1.4 on 2018-12-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinbasepay', '0007_auto_20181227_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargepayment',
            name='is_rewarded',
            field=models.BooleanField(default=False),
        ),
    ]
