# Generated by Django 2.1.4 on 2019-03-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grouppost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='converted_post',
            field=models.TextField(default=''),
        ),
    ]
