# Generated by Django 2.1.2 on 2018-11-02 16:14

from django.conf import settings
from django.db import migrations, models
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('short_about', models.CharField(max_length=300, verbose_name='Short About')),
                ('long_about', models.TextField(blank=True, null=True, verbose_name='Long About')),
                ('group_type', models.CharField(choices=[('1', 'Art'), ('2', 'Activist'), ('3', 'Political'), ('4', 'News'), ('5', 'Business'), ('6', 'Government'), ('7', 'Blog'), ('8', 'Nonprofit Organization'), ('9', 'Other')], max_length=30, verbose_name='Group Type')),
                ('group_type_other', models.CharField(blank=True, max_length=30, null=True, verbose_name='Please Specify')),
                ('join_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('request', 'Request'), ('invite', 'Invite')], default='open', max_length=30)),
                ('header_image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='group_headers')),
                ('logo', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='group_logos')),
                ('group_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('default_roles', models.TextField(default='superadmin;admin;moderator;member;subscriber', editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('auto_approve_post', models.BooleanField(blank=True, default=True)),
                ('auto_approve_comment', models.BooleanField(blank=True, default=True)),
                ('is_beta_test_group', models.BooleanField(default=False)),
                ('is_site_owner_group', models.BooleanField(default=False)),
                ('flagged_for_deletion', models.BooleanField(default=False)),
                ('flagged_for_deletion_on', models.DateTimeField(null=True)),
                ('admins', models.ManyToManyField(related_name='administerd_groups', to=settings.AUTH_USER_MODEL)),
                ('banned_members', models.ManyToManyField(related_name='banned_group', to=settings.AUTH_USER_MODEL)),
                ('blocked_members', models.ManyToManyField(related_name='blocked_group', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='joined_group', to=settings.AUTH_USER_MODEL)),
                ('moderators', models.ManyToManyField(related_name='moderating_groups', to=settings.AUTH_USER_MODEL)),
                ('staffs', models.ManyToManyField(related_name='staff_in_groups', to=settings.AUTH_USER_MODEL)),
                ('subscribers', models.ManyToManyField(related_name='subscribed_group', to=settings.AUTH_USER_MODEL)),
                ('super_admins', models.ManyToManyField(related_name='basicgroups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
