# Generated by Django 2.1.3 on 2018-11-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_groupinvite_groupmembernotification_inviteaccept_joinrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicgroup',
            name='long_about',
        ),
        migrations.RemoveField(
            model_name='basicgroup',
            name='short_about',
        ),
        migrations.AddField(
            model_name='basicgroup',
            name='about',
            field=models.CharField(default='', max_length=300, verbose_name='About'),
        ),
    ]
