# Generated by Django 2.1 on 2018-08-03 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stripepayment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('coin_name', models.CharField(max_length=100)),
                ('stripe_payment', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to='stripepayment.Payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='coinpurchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
