# Generated by Django 2.1 on 2018-08-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinpurchase', '0002_auto_20180803_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinpurchase',
            name='currency',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='coinpurchase',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coinpurchase',
            name='coin_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
