# Generated by Django 2.1.4 on 2018-12-27 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coinbasepay', '0007_auto_20181227_2232'),
        ('coinpurchase', '0003_auto_20180804_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinpurchase',
            name='coinbase_charge',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coinbasepay.Charge'),
        ),
        migrations.AlterField(
            model_name='coinpurchase',
            name='stripe_payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stripepayment.Payment'),
        ),
    ]
