# Generated by Django 2.1 on 2018-08-17 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BazaSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('incomplete', 'Incomplete')], default='pending', max_length=20)),
                ('photo', models.ImageField(null=True, upload_to='signup_images')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
                ('verified_date', models.DateTimeField(null=True)),
                ('referral_code', models.CharField(default='', max_length=6)),
                ('wallet_address', models.CharField(default='', max_length=40)),
                ('on_distribution', models.BooleanField(default=False)),
                ('completed_steps', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BazaSignupAdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('signup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bazasignup.BazaSignup')),
            ],
        ),
        migrations.CreateModel(
            name='BazaSignupAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('user_input', 'user_input'), ('twilio_db', 'twilio_db'), ('geoip_db', 'geoip_db')], max_length=20)),
                ('house_number', models.CharField(blank=True, default='', max_length=10)),
                ('street', models.CharField(blank=True, default='', max_length=200)),
                ('zip_code', models.CharField(blank=True, default='', max_length=10)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.CharField(blank=True, default='', max_length=100)),
                ('longitude', models.CharField(blank=True, default='', max_length=100)),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='bazasignup.BazaSignup')),
            ],
        ),
        migrations.CreateModel(
            name='BazaSignupEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('signups', models.ManyToManyField(related_name='signup_emails', to='bazasignup.BazaSignup')),
            ],
        ),
        migrations.CreateModel(
            name='BazaSignupPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('signups', models.ManyToManyField(related_name='signup_phones', to='bazasignup.BazaSignup')),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('verification_code', models.CharField(max_length=6)),
                ('created_on', models.DateTimeField()),
                ('signup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bazasignup.BazaSignup')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('verification_code', models.CharField(max_length=6)),
                ('created_on', models.DateTimeField()),
                ('signup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bazasignup.BazaSignup')),
            ],
        ),
    ]
