# Generated by Django 2.1 on 2018-08-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazasignup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazasignup',
            name='email_skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bazasignup',
            name='logged_ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='bazasignup',
            name='phone_skipped',
            field=models.BooleanField(default=False),
        ),
    ]
