# Generated by Django 2.1 on 2018-08-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazasignup', '0002_auto_20180822_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
