# Generated by Django 2.1.1 on 2018-09-13 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazasignup', '0005_bazasignupautoapprovalfailreason_bazasignupreferralcode_historicalbazasignupautoapprovalfailreason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bazasignup',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='historicalbazasignup',
            name='referral_code',
        ),
    ]
