# Generated by Django 2.1.4 on 2019-07-22 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bazasignup', '0006_auto_20180913_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazasignup',
            name='referred_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_signups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbazasignup',
            name='referred_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
