# Generated by Django 2.1.4 on 2019-07-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazasignup', '0007_auto_20190722_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazasignupreferralcode',
            name='code',
            field=models.CharField(max_length=12),
        ),
    ]
