# Generated by Django 2.1.4 on 2019-07-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazasignup', '0008_auto_20190725_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazasignup',
            name='is_donor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbazasignup',
            name='is_donor',
            field=models.BooleanField(default=False),
        ),
    ]
