# Generated by Django 2.1.5 on 2019-08-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazasignup', '0011_bazasignupcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazasignup',
            name='invalidated_steps',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalbazasignup',
            name='invalidated_steps',
            field=models.CharField(default='', max_length=10),
        ),
    ]
