# Generated by Django 2.1.5 on 2019-08-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazasignup', '0012_auto_20190817_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazasignupadditionalinfo',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalbazasignupadditionalinfo',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
