# Generated by Django 2.1.5 on 2019-08-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazasignup', '0013_auto_20190823_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazasignup',
            name='invalidated_steps',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalbazasignup',
            name='invalidated_steps',
            field=models.CharField(max_length=10),
        ),
    ]
