# Generated by Django 2.1.5 on 2019-08-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazasignup', '0014_auto_20190823_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazasignup',
            name='invalidated_fields',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='historicalbazasignup',
            name='invalidated_fields',
            field=models.CharField(default='', max_length=300),
        ),
    ]
