# Generated by Django 2.1.5 on 2019-08-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazasignup', '0015_auto_20190824_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazasignupadditionalinfo',
            name='invalidation_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalbazasignupadditionalinfo',
            name='invalidation_comment',
            field=models.TextField(default=''),
        ),
    ]
