# Generated by Django 2.1.5 on 2019-08-26 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bazasignup', '0016_auto_20190825_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazasignup',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignedbazasignups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbazasignup',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
