# Generated by Django 2.1.5 on 2019-08-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazasignup', '0018_staffloginsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffloginsession',
            name='logged_out_at',
            field=models.DateTimeField(null=True),
        ),
    ]
