# Generated by Django 2.1.5 on 2019-09-09 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bazasignup', '0019_auto_20190827_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='BazaSignupActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_assignment_activity', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_signup_activities', to=settings.AUTH_USER_MODEL)),
                ('related_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='bazasignup.BazaSignup')),
            ],
        ),
    ]
