# Generated by Django 2.1.5 on 2020-11-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazasignup', '0020_bazasignupactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazasignup',
            name='autoapproval_processed_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalbazasignup',
            name='autoapproval_processed_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bazasignup',
            name='photo',
            field=models.FileField(null=True, upload_to='signup_images'),
        ),
    ]
