# Generated by Django 2.1.5 on 2021-01-25 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazasignup', '0021_auto_20201112_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazasignupadditionalinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='historicalbazasignupadditionalinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
