# Generated by Django 2.1.4 on 2019-01-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtagimage',
            name='uid',
            field=models.CharField(default='', max_length=12),
        ),
    ]
