# Generated by Django 2.1.5 on 2019-12-21 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BountyProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('total_amount', models.PositiveIntegerField()),
                ('rewarded_amount', models.PositiveIntegerField(default=0)),
                ('enabled_for_site', models.BooleanField(default=False)),
                ('valid_till', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RewardedBounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewarded_for_task', models.CharField(default='', max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('bounty_program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewarded_users', to='bounty.BountyProgram')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewarded_bounties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
