# Generated by Django 2.1.5 on 2019-12-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxcdb', '0003_proxctransaction_coinpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxctransaction',
            name='should_substract_txfee',
            field=models.BooleanField(default=True),
        ),
    ]
