# Generated by Django 2.1.5 on 2022-06-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxcdb', '0004_proxctransaction_should_substract_txfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxctransaction',
            name='amount',
            field=models.FloatField(db_index=True),
        ),
    ]
