# Generated by Django 2.1.1 on 2018-09-23 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='userdocuments')),
            ],
        ),
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='userphotos')),
            ],
        ),
        migrations.RemoveField(
            model_name='userdocuments',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='userphotos',
            name='profile',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofilephoto',
            name='userphoto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profilephotos', to='userprofile.UserPhoto'),
        ),
        migrations.DeleteModel(
            name='UserDocuments',
        ),
        migrations.DeleteModel(
            name='UserPhotos',
        ),
        migrations.AddField(
            model_name='userphoto',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='userprofile.UserProfile'),
        ),
    ]
