# Generated by Django 2.1.1 on 2018-09-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20180923_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_avatar_color',
            field=models.CharField(default='#7b1fa2', max_length=8),
        ),
    ]
