# Generated by Django 2.1.1 on 2018-09-24 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20180923_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilephoto',
            name='userphoto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profilephotos', to='userprofile.UserPhoto'),
        ),
    ]
