# Generated by Django 2.1.1 on 2018-09-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20180924_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
