# Generated by Django 2.1.1 on 2018-09-29 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_userprofile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('phone_number_type', models.CharField(choices=[('office', 'Office'), ('home', 'Home'), ('mobile', 'Mobile'), ('emergency', 'Emergency')], default='office', max_length=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='userprofile.UserProfile')),
            ],
        ),
    ]
