# Generated by Django 2.1.1 on 2018-10-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_userphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphone',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
