# Generated by Django 2.1.2 on 2018-10-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_usertwofactor_usertwofactorrecovery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertwofactor',
            old_name='verified',
            new_name='enabled',
        ),
    ]
