# Generated by Django 2.1.3 on 2018-11-23 22:25

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_auto_20181013_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='document',
            field=models.FileField(upload_to=userprofile.models.user_directory),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='photo',
            field=models.ImageField(upload_to=userprofile.models.user_directory),
        ),
    ]
