# Generated by Django 2.1.3 on 2018-12-08 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0014_auto_20181123_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_and_validated_email', models.BooleanField(default=False)),
                ('added_location', models.BooleanField(default=False)),
                ('added_two_factor_authentication', models.BooleanField(default=False)),
                ('linked_one_social_account', models.BooleanField(default=False)),
                ('completed_distribution_signup', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
