# Generated by Django 2.1.3 on 2018-12-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_usertasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphone',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
