# Generated by Django 2.1.3 on 2018-12-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0018_auto_20181212_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertasks',
            name='added_and_validated_phone',
            field=models.BooleanField(default=False),
        ),
    ]
