# Generated by Django 2.1.4 on 2019-02-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0022_auto_20190212_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphone',
            name='phone_number_country_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
