# Generated by Django 2.1.5 on 2020-11-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0024_usertasks_added_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertasks',
            name='completed_distribution_signup',
        ),
        migrations.AddField(
            model_name='usertasks',
            name='uploaded_an_official_document_id',
            field=models.BooleanField(default=False),
        ),
    ]
