# Generated by Django 2.1.5 on 2020-12-01 21:02

from django.db import migrations
import userprofile.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0025_auto_20201104_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='document',
            field=versatileimagefield.fields.VersatileImageField(upload_to=userprofile.models.user_directory),
        ),
    ]
