# Generated by Django 2.1.5 on 2020-12-01 21:24

from django.db import migrations
import userprofile.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0026_auto_20201201_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='photo',
            field=versatileimagefield.fields.VersatileImageField(upload_to=userprofile.models.user_directory),
        ),
    ]
