# Generated by Django 2.1 on 2018-08-03 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('is_success', models.BooleanField(default=False)),
                ('message', models.CharField(default='', max_length=250)),
                ('payment_type', models.CharField(default='', max_length=100)),
                ('fail_reason', models.CharField(default='', max_length=300)),
                ('charge_id', models.CharField(default='', max_length=200)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
